name: Doc Analysis (DISABLED - using hot-path.yml instead)

# DISABLED: This workflow is replaced by hot-path.yml
# To re-enable, uncomment the 'on:' section below
on: workflow_dispatch  # Manual trigger only

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#   issue_comment:
#     types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # need merge-base for diffs

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r scripts/requirements.txt

      - name: Run analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          DOCS_DIR: docs
          DOCS_EXTRAS: README.md  # comma-separated list
        run: python scripts/analyze_pr.py

  update-docs:
    # Slash command approval
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/update-docs')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('ref', pr.data.head.ref);
            core.setOutput('sha', pr.data.head.sha);
            core.setOutput('base_sha', pr.data.base.sha);
            core.setOutput('base_ref', pr.data.base.ref);

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ steps.pr.outputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r scripts/requirements.txt || true

      - name: Commit doc stubs and update comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          BASE_SHA: ${{ steps.pr.outputs.base_sha }}   # filled now
          HEAD_SHA: ${{ steps.pr.outputs.sha }}        # filled now
          BASE_REF: ${{ steps.pr.outputs.base_ref }}   # fallback help
          DOCS_DIR: docs
          DOCS_EXTRAS: README.md
        run: python scripts/update_docs.py
