name: Sync docs to Wiki

on:
  push:
    branches: ['**']
    paths:
      - 'docs/**'
      - '.github/workflows/wiki-sync.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Ensure wiki exists
        run: |
          if ! git ls-remote "https://github.com/${{ github.repository }}.wiki.git" &>/dev/null; then
            echo "Initialize the wiki once: Repo → Wiki → 'Create the first page'. Then re-run."
            exit 1
          fi

      - name: Clone wiki repo
        run: |
          git clone "https://github.com/${{ github.repository }}.wiki.git" wiki

      - name: Sync docs to wiki (preserve .git)
        run: |
          rsync -av --delete \
            --exclude '.git' --exclude '.git/**' \
            --exclude '.github' \
            docs/ wiki/

          # Optional: set a Home page if missing
          if [ ! -f wiki/Home.md ]; then
            for f in Overview.md README.md index.md; do
              if [ -f "wiki/$f" ]; then cp "wiki/$f" "wiki/Home.md"; break; fi
            done
          fi

      - name: Commit & push to wiki (with token)
        working-directory: wiki
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync docs from repo docs/" || echo "No changes"

          # Set authenticated remote and push
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git"
          git config --global --add safe.directory $(pwd)
          git push origin HEAD:master
